while(True):
    n=int(input())
    if(n==9999):
        break
    else:
        if(90<=n<=100):
            print("A")
        elif(80<=n<90):
            print("B")
        elif(70<=n<80):
            print("C")
        elif(60<=n<70):
            print("D")
        elif(0<=n<60):
            print("E")
